// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "vzlprclientctrlctrl1.h"

/////////////////////////////////////////////////////////////////////////////
// CVzlprclientctrlctrl1

IMPLEMENT_DYNCREATE(CVzlprclientctrlctrl1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CVzlprclientctrlctrl1 properties

/////////////////////////////////////////////////////////////////////////////
// CVzlprclientctrlctrl1 operations
